return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
        local configs = require("nvim-treesitter.configs")

        configs.setup({
            ensure_installed = {
                "astro",
                "bash",
                "c",
                "comment",
                "css",
                "csv",
                "diff",
                "dockerfile",
                "editorconfig",
                "elixir",
                "git_config",
                "git_rebase",
                "gitcommit",
                "gitignore",
                "go",
                "graphql",
                "hcl",
                "heex",
                "html",
                "javascript",
                "jq",
                "json",
                "lua",
                "luadoc",
                "make",
                "markdown",
                "markdown_inline",
                "nginx",
                "php",
                "prisma",
                "python",
                "query",
                "ruby",
                "rust",
                "solidity",
                "sql",
                "svelte",
                "toml",
                "tsx",
                "typescript",
                "vue",
                "wing",
                "yaml",
                "zig",
            },
            highlight = { enable = true, additional_vim_regex_highlighting = false },
            indent = { enable = false },
        })
    end,
}
